### PR TITLE
Add missing forestry module data

### PR DESCRIPTION
**Pull request by rduivenvoorde**
This data for module 'forestry' was missing.

I added it here, and think we should add it to branch 'release_3.10' and 'v2.0' too ?

Note that I got some warnings: 

```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File exercise_data/forestry/rautjarvi_aerial.tif is 88.62 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File exercise_data/forestry/rautjarvi_map.tif is 66.36 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

But apparently it is still ok...

### CODE REVIEW

**Comment by havatv** [comment]
Some hours ago, I tried to add the same (forestry) data + the *more_analysis* data, but that failed:

`error: File exercise_data/more_analysis/DEM/reprojected/DEM is 200.09 MB; this exceeds GitHub's file size limit of 100.00 MB`.

So, some parallel efforts here :-).

**Comment by rduivenvoorde** [comment]
>  Should it also be added to the v2.0 branc?

Yes, else it will not show up in the 3.4 zip url...

About the reprojected dem... I think it should be possible to stay below 100Mb for that? Redefine the excercise or so? Else.... I dunno, we can put it https://qgis.org/downloads/data/

**Comment by DelazJ** [comment]
> A few hours ago, I tried to add the same (forestry) data + the more_analysis data, but that failed:

>error: File exercise_data/more_analysis/DEM/reprojected/DEM is 200.09 MB; this exceeds GitHub's file size limit of 100.00 MB.

And me years ago https://github.com/qgis/QGIS-Website/issues/216#issuecomment-238101205 Maybe the git lfs status has evolved since...

Having all the data in the repo would be my favorite option but I agree we better store them in qgis.org than putting them in a ****box and lose them **again**.
Thanks @rduivenvoorde for taking care of this. I think there might be other files we would need to move from v2.0 to master but I do not recall which ones (sorry). Will try next week to check the two branches and align master with lessons.

**Comment by rduivenvoorde** [comment]
FYI I just sent an email to github to see if they can maybe raise the limit of these two repo's, with the argument that these files are actually rather static...
See what comes...

**Comment by rduivenvoorde** [comment]
Another idea... host it at: https://git.osgeo.org/ ? Though I would ask SAC first for that...
Also checked gitlab.com, but they even have lower size limits...

**Pull request merged**
